
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DO DOT ELSE EQ FOR GT ID IF LBRACE LPAREN LT NUMBER PLUS PRINT RBRACE RPAREN SEMI STRING WHILEstatements : statement statements\n                  | statementstatement : IF LPAREN expression RPAREN blockstatement : FOR LPAREN statement expression SEMI expression RPAREN blockstatement : DO block WHILE LPAREN expression RPAREN SEMIstatement : WHILE LPAREN expression RPAREN blockstatement : PRINT LPAREN expression RPAREN SEMIstatement : expression SEMIblock : LBRACE statements RBRACE\n             | LBRACE RBRACEexpression : expression GT expression\n                  | expression LT expression\n                  | expression EQ expression\n                  | expression PLUS expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : IDexpression : STRINGempty :'
    
_lr_action_items = {'IF':([0,2,16,21,23,35,41,44,47,48,52,53,],[3,3,-8,3,3,-10,-9,-3,-6,-7,-5,-4,]),'FOR':([0,2,16,21,23,35,41,44,47,48,52,53,],[6,6,-8,6,6,-10,-9,-3,-6,-7,-5,-4,]),'DO':([0,2,16,21,23,35,41,44,47,48,52,53,],[7,7,-8,7,7,-10,-9,-3,-6,-7,-5,-4,]),'WHILE':([0,2,16,21,22,23,35,41,44,47,48,52,53,],[8,8,-8,8,33,8,-10,-9,-3,-6,-7,-5,-4,]),'PRINT':([0,2,16,21,23,35,41,44,47,48,52,53,],[9,9,-8,9,9,-10,-9,-3,-6,-7,-5,-4,]),'LPAREN':([0,2,3,4,6,8,9,14,16,17,18,19,20,21,23,24,25,32,33,35,40,41,44,45,47,48,52,53,],[4,4,14,4,21,24,25,4,-8,4,4,4,4,4,4,4,4,4,40,-10,4,-9,-3,4,-6,-7,-5,-4,]),'NUMBER':([0,2,4,14,16,17,18,19,20,21,23,24,25,32,35,40,41,44,45,47,48,52,53,],[10,10,10,10,-8,10,10,10,10,10,10,10,10,10,-10,10,-9,-3,10,-6,-7,-5,-4,]),'ID':([0,2,4,14,16,17,18,19,20,21,23,24,25,32,35,40,41,44,45,47,48,52,53,],[11,11,11,11,-8,11,11,11,11,11,11,11,11,11,-10,11,-9,-3,11,-6,-7,-5,-4,]),'STRING':([0,2,4,14,16,17,18,19,20,21,23,24,25,32,35,40,41,44,45,47,48,52,53,],[12,12,12,12,-8,12,12,12,12,12,12,12,12,12,-10,12,-9,-3,12,-6,-7,-5,-4,]),'$end':([1,2,13,16,35,41,44,47,48,52,53,],[0,-2,-1,-8,-10,-9,-3,-6,-7,-5,-4,]),'RBRACE':([2,13,16,23,34,35,41,44,47,48,52,53,],[-2,-1,-8,35,41,-10,-9,-3,-6,-7,-5,-4,]),'SEMI':([5,10,11,12,27,28,29,30,31,39,43,50,],[16,-16,-17,-18,-15,-11,-12,-13,-14,45,48,52,]),'GT':([5,10,11,12,15,26,27,28,29,30,31,36,37,39,46,49,],[17,-16,-17,-18,17,17,-15,17,17,17,17,17,17,17,17,17,]),'LT':([5,10,11,12,15,26,27,28,29,30,31,36,37,39,46,49,],[18,-16,-17,-18,18,18,-15,18,18,18,18,18,18,18,18,18,]),'EQ':([5,10,11,12,15,26,27,28,29,30,31,36,37,39,46,49,],[19,-16,-17,-18,19,19,-15,19,19,19,19,19,19,19,19,19,]),'PLUS':([5,10,11,12,15,26,27,28,29,30,31,36,37,39,46,49,],[20,-16,-17,-18,20,20,-15,20,20,20,20,20,20,20,20,20,]),'LBRACE':([7,38,42,51,],[23,23,23,23,]),'RPAREN':([10,11,12,15,26,27,28,29,30,31,36,37,46,49,],[-16,-17,-18,27,38,-15,-11,-12,-13,-14,42,43,50,51,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,2,23,],[1,13,34,]),'statement':([0,2,21,23,],[2,2,32,2,]),'expression':([0,2,4,14,17,18,19,20,21,23,24,25,32,40,45,],[5,5,15,26,28,29,30,31,5,5,36,37,39,46,49,]),'block':([7,38,42,51,],[22,44,47,53,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statement statements','statements',2,'p_statements','views.py',68),
  ('statements -> statement','statements',1,'p_statements','views.py',69),
  ('statement -> IF LPAREN expression RPAREN block','statement',5,'p_statement_if','views.py',76),
  ('statement -> FOR LPAREN statement expression SEMI expression RPAREN block','statement',8,'p_statement_for','views.py',80),
  ('statement -> DO block WHILE LPAREN expression RPAREN SEMI','statement',7,'p_statement_do','views.py',84),
  ('statement -> WHILE LPAREN expression RPAREN block','statement',5,'p_statement_while','views.py',88),
  ('statement -> PRINT LPAREN expression RPAREN SEMI','statement',5,'p_statement_print','views.py',92),
  ('statement -> expression SEMI','statement',2,'p_statement_expr','views.py',96),
  ('block -> LBRACE statements RBRACE','block',3,'p_block','views.py',100),
  ('block -> LBRACE RBRACE','block',2,'p_block','views.py',101),
  ('expression -> expression GT expression','expression',3,'p_expression_binop','views.py',108),
  ('expression -> expression LT expression','expression',3,'p_expression_binop','views.py',109),
  ('expression -> expression EQ expression','expression',3,'p_expression_binop','views.py',110),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','views.py',111),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','views.py',115),
  ('expression -> NUMBER','expression',1,'p_expression_number','views.py',119),
  ('expression -> ID','expression',1,'p_expression_id','views.py',123),
  ('expression -> STRING','expression',1,'p_expression_string','views.py',127),
  ('empty -> <empty>','empty',0,'p_empty','views.py',131),
]
