
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOT ID LEFT_BRACE LEFT_PAREN PR_FUNC PR_IMPORT PR_PACKAGE RIGHT_BRACE RIGHT_PAREN STRINGprogram : PR_PACKAGE ID\n               | PR_IMPORT STRING\n               | PR_FUNC ID LEFT_PAREN RIGHT_PAREN LEFT_BRACE statement RIGHT_BRACEstatement : ID DOT ID LEFT_PAREN STRING RIGHT_PAREN'
    
_lr_action_items = {'PR_PACKAGE':([0,],[2,]),'PR_IMPORT':([0,],[3,]),'PR_FUNC':([0,],[4,]),'$end':([1,5,6,14,],[0,-1,-2,-3,]),'ID':([2,4,10,13,],[5,7,11,15,]),'STRING':([3,16,],[6,17,]),'LEFT_PAREN':([7,15,],[8,16,]),'RIGHT_PAREN':([8,17,],[9,18,]),'LEFT_BRACE':([9,],[10,]),'DOT':([11,],[13,]),'RIGHT_BRACE':([12,18,],[14,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([10,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PR_PACKAGE ID','program',2,'p_program','views.py',43),
  ('program -> PR_IMPORT STRING','program',2,'p_program','views.py',44),
  ('program -> PR_FUNC ID LEFT_PAREN RIGHT_PAREN LEFT_BRACE statement RIGHT_BRACE','program',7,'p_program','views.py',45),
  ('statement -> ID DOT ID LEFT_PAREN STRING RIGHT_PAREN','statement',6,'p_statement','views.py',48),
]
