
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID LEFT_BRACE LEFT_PAREN LESSTHANOREQUALS NUMBER PLUS PR_FOR PR_INT RIGHT_BRACE RIGHT_PAREN SEMICOLONstatement : PR_FOR LEFT_PAREN PR_INT ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE statement_list RIGHT_BRACE\n                 | PR_FOR LEFT_PAREN ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE statement_list RIGHT_BRACE\n                 | PR_FOR LEFT_PAREN PR_INT ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE RIGHT_BRACE\n                 | PR_FOR LEFT_PAREN ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE RIGHT_BRACEstatement_list : statement\n                      | statement statement_liststatement : '
    
_lr_action_items = {'PR_FOR':([0,29,30,32,33,35,36,38,],[2,2,2,-4,2,-3,-2,-1,]),'$end':([0,1,32,35,36,38,],[-7,0,-4,-3,-2,-1,]),'LEFT_PAREN':([2,],[3,]),'PR_INT':([3,],[4,]),'ID':([3,4,11,12,19,20,],[5,6,13,14,21,22,]),'EQUALS':([5,6,],[7,8,]),'NUMBER':([7,8,15,16,],[9,10,17,18,]),'SEMICOLON':([9,10,17,18,],[11,12,19,20,]),'LESSTHANOREQUALS':([13,14,],[15,16,]),'PLUS':([21,22,23,24,],[23,24,25,26,]),'RIGHT_PAREN':([25,26,],[27,28,]),'LEFT_BRACE':([27,28,],[29,30,]),'RIGHT_BRACE':([29,30,31,32,33,34,35,36,37,38,],[32,35,36,-4,-5,38,-3,-2,-6,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,29,30,33,],[1,33,33,33,]),'statement_list':([29,30,33,],[31,34,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PR_FOR LEFT_PAREN PR_INT ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE statement_list RIGHT_BRACE','statement',18,'p_statement','views.py',272),
  ('statement -> PR_FOR LEFT_PAREN ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE statement_list RIGHT_BRACE','statement',17,'p_statement','views.py',273),
  ('statement -> PR_FOR LEFT_PAREN PR_INT ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE RIGHT_BRACE','statement',17,'p_statement','views.py',274),
  ('statement -> PR_FOR LEFT_PAREN ID EQUALS NUMBER SEMICOLON ID LESSTHANOREQUALS NUMBER SEMICOLON ID PLUS PLUS RIGHT_PAREN LEFT_BRACE RIGHT_BRACE','statement',16,'p_statement','views.py',275),
  ('statement_list -> statement','statement_list',1,'p_statement_list','views.py',279),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list','views.py',280),
  ('statement -> <empty>','statement',0,'p_statement_empty','views.py',284),
]
